add snapshot testing docs
dendronhq/dendron-docs pull request #18
Opened 2022-02-18 20:47 UTC by hikchoi

This PR:
- adds guide to snapshot testing

2022-02-19 20:28 UTC, SeriousBug approved these changes
Looks good to me. Would you also mind adding an item to PR review SOP that if there are changes to snapshots, the changes should be checked to make sure they are justified/make sense? I think it's easy to gloss over the snapshot changes when reviewing a PR.

2022-02-21 05:18 UTC, jonathanyeung commented on vault/dev.process.qa.test.snapshot-testing.md
> +While snapshot tests provides us with some great power, it has drawbacks when we don't be mindful about using them.
nit: when we aren't mindful

2022-02-21 17:57 UTC, kevinslin requested changes
nice writeup. can you create a section in [[Testing|dendron://dendron.docs/dev.process.qa.test]] about snapshot testing and link to this note? I find that notes aren't discoverable unless we explicitly create links to them

2022-02-25 14:45 UTC, hikchoi commented
suggestions applied

2022-06-07 15:27 UTC, hikchoi commented
closing this out and updating the docs separately.

2022-06-07 15:27 UTC, closed without merging